import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Nunito_Sans } from 'next/font/google';
const nunitoSans = Nunito_Sans({ subsets: ["latin"], weight: "700" });
import { dark, shadesOfPurple } from '@clerk/themes'

import "./globals.css";
import { ClerkProvider, ClerkLoaded, ClerkLoading } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: shadesOfPurple,
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <ClerkLoading>
            <div className="flex items-center justify-center h-screen">
              <span className="styled-text">Striide</span>
            </div>
          </ClerkLoading>

          <ClerkLoaded>
            <div className="flex flex-col items-center justify-center h-screen">
              <div className="w-full max-w-xs md:max-w-md lg:max-w-lg xl:max-w-xl">
                {children}
              </div>
            </div>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}