import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Nunito_Sans } from 'next/font/google';
const nunitoSans = Nunito_Sans({ subsets: ["latin"], weight: "700" });
import { dark, shadesOfPurple } from '@clerk/themes'

import "./globals.css";
import { ClerkProvider, ClerkLoaded, ClerkLoading, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: shadesOfPurple,
      }}
    >
      <html lang="en" className="h-full">
        <body className={`${inter.className} h-full`}>
          <ClerkLoading>
            <div className="flex items-center justify-center h-screen bg-gradient-to-tr from-[#3A00A4] to-[#802EE8]">
              <span className="styled-text">Striide</span>
            </div>
          </ClerkLoading>

          <ClerkLoaded>
            <div className="min-h-screen bg-gradient-to-tr from-[#3A00A4] to-[#802EE8]">
              {children}
            </div>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}