import type { Metadata } from "next";
import { Nunito_Sans } from 'next/font/google';
const nunitoSans = Nunito_Sans({ subsets: ["latin"], weight: "400" });
import { shadesOfPurple } from '@clerk/themes'
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Striide",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: shadesOfPurple,
      }}
    >
      <html lang="en" className="h-full">
        <body className={`${nunitoSans.className} h-full`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}